// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wardrobe.Data;

#nullable disable

namespace Wardrobe.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240402160705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wardrobe.Models.PairOfShoes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PairOfShoes");
                });

            modelBuilder.Entity("Wardrobe.Models.WearCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PairOfShoesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimesWorn")
                        .HasColumnType("int");

                    b.Property<DateTime>("WearDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PairOfShoesId");

                    b.ToTable("WearCounter");
                });

            modelBuilder.Entity("Wardrobe.Models.WearCounter", b =>
                {
                    b.HasOne("Wardrobe.Models.PairOfShoes", null)
                        .WithMany("ShoeWearCounter")
                        .HasForeignKey("PairOfShoesId");
                });

            modelBuilder.Entity("Wardrobe.Models.PairOfShoes", b =>
                {
                    b.Navigation("ShoeWearCounter");
                });
#pragma warning restore 612, 618
        }
    }
}
